# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 172f8623b5ba8ae7a3580a19c9c4e4f7516cb9ad9a87cb3dde73dbc17c4b54cfb9698f0f1307055a893d6bc929bd6472eb38a7884ce41d664e688946cbd6f668

test:
  secret_key_base: 14dd56f34a531bdac9c5e5b6a7388ef593b647ab064746e68056dbfccb9acafc724eec6ff12b05b7026be64700272a532eec7b32ae7e95c51f75c71fc71110dc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
